// data.js

// Data sins dan panduan
export const sinsData = [
  {
    id: 1,
    type: 'major',
    name: 'Syirik (Menyekutukan Allah)',
    description: 'Dosa terbesar dalam Islam. Menyekutukan Allah dengan makhluk lain dalam ibadah. Allah tidak akan mengampuni dosa syirik jika tidak bertaubat sebelum meninggal.',
    source: 'QS. An-Nisa: 48',
    repentance: 'Taubat dari syirik adalah dengan mengesakan Allah SWT, bersyahadat kembali, dan bertekad tidak akan pernah mengulanginya.',
    repentanceSource: '“Sesungguhnya Allah tidak akan mengampuni dosa syirik, dan Dia mengampuni segala dosa yang selain dari (syirik) itu, bagi siapa yang dikehendaki-Nya.” (QS. An-Nisa: 48).',
  },
  {
    id: 2,
    type: 'major',
    name: 'Membunuh Jiwa Tanpa Hak',
    description: 'Membunuh jiwa yang diharamkan Allah adalah dosa besar. Allah melarang perbuatan ini dan menjanjikan balasan yang setimpal.',
    source: 'QS. Al-Maidah: 32',
    repentance: 'Taubatnya harus dengan penyesalan yang mendalam dan memohon ampunan kepada Allah. Jika korban memiliki wali atau ahli waris, harus meminta maaf dan menawarkan diyat (kompensasi) sesuai syariat.',
    repentanceSource: '“...Barangsiapa yang membunuh seorang manusia, bukan karena orang itu (membunuh) orang lain, atau bukan karena membuat kerusakan dimuka bumi, maka seakan-akan dia telah membunuh manusia seluruhnya.” (QS. Al-Maidah: 32).',
  },
  {
    id: 3,
    type: 'major',
    name: 'Sihir',
    description: 'Melakukan atau mempelajari sihir termasuk dosa besar karena perbuatan ini bersekutu dengan jin dan dapat merusak manusia lain.',
    source: 'HR. Bukhari',
    repentance: 'Taubat dari sihir sangat sulit dan membutuhkan penyesalan mendalam, kembali kepada Allah, dan meninggalkan semua praktik sihir. Jika sihir dilakukan kepada orang lain, harus meminta maaf dan mengembalikan hak mereka.',
    repentanceSource: '“Jauhilah tujuh perkara yang membinasakan.” Para sahabat bertanya, “Apa itu, wahai Rasulullah?” Beliau menjawab, “Syirik kepada Allah, sihir...” (HR. Bukhari & Muslim).',
  },
  {
    id: 4,
    type: 'major',
    name: 'Makan Harta Anak Yatim',
    description: 'Mengambil atau memakan harta anak yatim secara zalim adalah perbuatan yang sangat dikecam dalam Al-Qur\'an.',
    source: 'QS. An-Nisa: 10',
    repentance: 'Taubatnya adalah dengan mengembalikan harta anak yatim yang telah diambil, meminta maaf kepada wali anak yatim, dan beristighfar dengan sungguh-sungguh.',
    repentanceSource: '“Sesungguhnya orang-orang yang memakan harta anak yatim secara zalim, sebenarnya mereka itu menelan api sepenuh perutnya dan mereka akan masuk ke dalam api yang menyala-nyala (neraka).” (QS. An-Nisa: 10).',
  },
  {
    id: 5,
    type: 'major',
    name: 'Meninggalkan Shalat Wajib',
    description: 'Meninggalkan shalat lima waktu adalah dosa besar karena shalat adalah tiang agama dan kewajiban utama seorang Muslim.',
    source: 'Hadis Riwayat Tirmidzi',
    repentance: 'Taubatnya adalah dengan menyesali perbuatan, segera kembali mendirikan shalat, dan bertekad untuk tidak pernah meninggalkannya lagi. Perbanyak shalat sunnah untuk menutupi kekurangan.',
    repentanceSource: '“Pangkal segala urusan adalah Islam. Tiangnya adalah shalat, dan puncaknya adalah jihad di jalan Allah.” (HR. Tirmidzi).',
  },
  {
    id: 6,
    type: 'major',
    name: 'Durhaka kepada Orang Tua',
    description: 'Berbuat durhaka (berkata kasar, tidak patuh, atau menyakiti hati) kepada orang tua adalah dosa besar.',
    source: 'HR. Bukhari & Muslim',
    repentance: 'Berhenti bersikap durhaka, meminta maaf dan keridhaan dari kedua orang tua dengan tulus. Jika salah satunya sudah meninggal, banyaklah berdoa untuk mereka dan bersedekah atas nama mereka.',
    repentanceSource: '“Keridhaan Allah terletak pada keridhaan orang tua, dan kemurkaan Allah terletak pada kemurkaan orang tua.” (HR. At-Tirmidzi).',
  },
  {
    id: 7,
    type: 'major',
    name: 'Makan Riba',
    description: 'Melakukan transaksi yang mengandung riba, seperti mengambil atau memberi bunga, adalah dosa besar.',
    source: 'QS. Al-Baqarah: 275',
    repentance: 'Berhenti dari segala transaksi riba, menyesali perbuatan, dan berjanji tidak akan mengulanginya. Kembalikan semua harta riba yang telah didapatkan.',
    repentanceSource: '“...Padahal Allah telah menghalalkan jual beli dan mengharamkan riba.” (QS. Al-Baqarah: 275).',
  },
  {
    id: 8,
    type: 'major',
    name: 'Zina',
    description: 'Melakukan hubungan seksual di luar ikatan pernikahan yang sah adalah dosa besar.',
    source: 'QS. Al-Isra\': 32',
    repentance: 'Menyesalinya dengan sungguh-sungguh, bertekad tidak mengulangi, dan memperbanyak amal kebaikan. Jaga pandangan dan hindari tempat-tempat yang dapat menjerumuskan.',
    repentanceSource: '“Dan janganlah kamu mendekati zina; sesungguhnya zina itu adalah suatu perbuatan yang keji. Dan suatu jalan yang buruk.” (QS. Al-Isra\': 32).',
  },
  {
    id: 9,
    type: 'minor',
    name: 'Berbohong',
    description: 'Berbohong adalah salah satu tanda munafik. Meskipun kadang dianggap sepele, jika terus-menerus dilakukan dapat mengarah ke dosa besar.',
    source: 'Hadis Riwayat Bukhari',
    repentance: 'Taubat dari kebohongan adalah dengan berhenti berbohong, menyesalinya, dan berusaha selalu berkata jujur. Jika kebohongan merugikan orang lain, maka harus meminta maaf.',
    repentanceSource: '“Jujurlah, karena sesungguhnya kejujuran itu menuntun kepada kebaikan, dan kebaikan itu menuntun ke surga.” (HR. Bukhari & Muslim).',
  },
  {
    id: 10,
    type: 'minor',
    name: 'Mendengarkan Ghibah',
    description: 'Mendengarkan ghibah (membicarakan aib orang lain) sama buruknya dengan melakukan ghibah itu sendiri, yaitu dosa minor yang dapat berakumulasi.',
    source: 'Hadis Riwayat Abu Daud',
    repentance: 'Taubatnya adalah dengan tidak lagi mendengarkan ghibah, menasehati orang yang sedang berghibah, dan mendoakan ampunan bagi orang yang digunjingkan.',
    repentanceSource: '“...Dan janganlah sebagian kalian menggunjing (ghibah) sebagian yang lain. Sukakah salah seorang di antara kalian memakan daging saudaranya yang sudah mati?” (QS. Al-Hujurat: 12).',
  },
  {
    id: 11,
    type: 'minor',
    name: 'Berlebihan Dalam Makanan',
    description: 'Israf (berlebihan) dalam makan atau minum termasuk perbuatan yang dibenci oleh Allah.',
    source: 'QS. Al-A\'raf: 31',
    repentance: 'Taubatnya adalah dengan tidak lagi berlebihan, bersyukur atas nikmat yang ada, dan bertekad untuk makan secukupnya.',
    repentanceSource: '“...Makan dan minumlah, dan janganlah berlebih-lebihan. Sesungguhnya Allah tidak menyukai orang-orang yang berlebih-lebihan.” (QS. Al-A\'raf: 31).',
  },
  {
    id: 12,
    type: 'minor',
    name: 'Melihat Aurat yang Diharamkan',
    description: 'Melihat hal-hal yang tidak senonoh atau aurat yang haram adalah dosa kecil.',
    source: 'QS. An-Nur: 30',
    repentance: 'Taubatnya adalah dengan segera mengalihkan pandangan, menyesalinya, dan beristighfar. Berusaha menjaga pandangan dari hal-hal yang tidak senonoh.',
    repentanceSource: '“Katakanlah kepada orang laki-laki yang beriman: ‘Hendaklah mereka menahan pandangannya, dan memelihara kemaluannya...’” (QS. An-Nur: 30).',
  },
  {
    id: 13,
    type: 'minor',
    name: 'Membenci Sesama Muslim',
    description: 'Membenci saudara sesama Muslim tanpa alasan yang dibenarkan syariat adalah dosa.',
    source: 'Hadis Riwayat Bukhari & Muslim',
    repentance: 'Taubatnya adalah dengan menghilangkan kebencian dari hati, meminta maaf kepada orang yang dibenci, dan mendoakan kebaikan untuknya.',
    repentanceSource: '“Tidak halal bagi seorang muslim mendiamkan (tidak menyapa) saudaranya lebih dari tiga hari.” (HR. Bukhari & Muslim).',
  },
  {
    id: 14,
    type: 'minor',
    name: 'Terlambat dalam Shalat',
    description: 'Menunda shalat dari waktu yang ditentukan tanpa alasan syar\'i.',
    source: 'HR. At-Tirmidzi',
    repentance: 'Menyesalinya, bertekad untuk shalat tepat waktu, dan memperbanyak shalat sunnah untuk menutupi kekurangan.',
    repentanceSource: '“Amal yang paling dicintai Allah adalah shalat tepat pada waktunya.” (HR. Bukhari & Muslim).',
  },
  {
    id: 15,
    type: 'minor',
    name: 'Menyakiti Hewan',
    description: 'Berbuat zalim atau menyakiti hewan tanpa sebab yang dibenarkan.',
    source: 'HR. Muslim',
    repentance: 'Menyesalinya, beristighfar, dan berbuat baik kepada hewan. Perbaiki perlakuan Anda terhadap hewan di masa depan.',
    repentanceSource: '“Ada seorang wanita yang masuk neraka karena seekor kucing yang ia kurung, ia tidak memberinya makan dan tidak pula melepaskannya agar bisa mencari makan dari serangga tanah.” (HR. Bukhari & Muslim).',
  },
  {
    id: 16,
    type: 'minor',
    name: 'Menonton Pornografi',
    description: 'Menonton pornografi adalah dosa kecil yang dapat mengarah pada dosa besar. Ini adalah pelanggaran terhadap perintah untuk menundukkan pandangan.',
    source: 'QS. An-Nur: 30',
    repentance: 'Taubatnya adalah dengan segera menghentikan kebiasaan tersebut, menghapus semua materi yang tidak pantas, dan memperbanyak istighfar. Berlatih menundukkan pandangan dari hal-hal yang haram.',
    repentanceSource: '“Katakanlah kepada orang laki-laki yang beriman: ‘Hendaklah mereka menahan pandangannya, dan memelihara kemaluannya...’” (QS. An-Nur: 30).',
  },
  {
    id: 17,
    type: 'minor',
    name: 'Berbuka Aurat di Media Sosial',
    description: 'Mempertontonkan aurat, terutama di media sosial seperti TikTok, adalah perbuatan yang dapat mendatangkan dosa karena menarik perhatian yang tidak halal.',
    source: 'HR. Muslim',
    repentance: 'Taubatnya adalah dengan menghapus konten yang memperlihatkan aurat dan bertekad untuk tidak mengunggahnya lagi. Perbanyak beristighfar dan berhijab dengan benar di dunia nyata maupun virtual.',
    repentanceSource: 'Rasulullah SAW bersabda, “Ada dua golongan dari penduduk neraka yang belum pernah aku lihat: ... wanita-wanita yang berpakaian (tapi) telanjang, berjalan melenggak-lenggok, kepala mereka seperti punuk unta yang miring. Wanita seperti ini tidak akan masuk surga, bahkan tidak mencium baunya.” (HR. Muslim).',
  },
  {
    id: 18,
    type: 'major',
    name: 'Kredit dan Utang Riba',
    description: 'Mengambil pinjaman atau kredit dari bank dengan sistem bunga (riba) adalah dosa besar, karena riba diharamkan oleh Allah SWT.',
    source: 'QS. Al-Baqarah: 275',
    repentance: 'Taubatnya adalah dengan menghentikan transaksi riba, menyesali perbuatan, dan berusaha melunasi utang secepatnya. Bertekad untuk tidak pernah kembali ke transaksi riba.',
    repentanceSource: '“...Padahal Allah telah menghalalkan jual beli dan mengharamkan riba.” (QS. Al-Baqarah: 275).',
  },
  {
    id: 19,
    type: 'major',
    name: 'Mengintip Wanita Mandi',
    description: 'Mengintip atau melihat aurat seseorang tanpa izin, terutama dalam keadaan tidak berbusana, adalah perbuatan yang sangat keji dan terlarang.',
    source: 'HR. Bukhari & Muslim',
    repentance: 'Taubatnya adalah dengan penyesalan yang mendalam, tidak mengulangi perbuatan tersebut, dan meminta ampunan kepada Allah. Jika memungkinkan, minta maaf kepada orang yang bersangkutan tanpa membongkar aibnya, dan perbanyak istighfar.',
    repentanceSource: '“Barangsiapa yang mengintip ke dalam rumah suatu kaum tanpa izin mereka, maka sungguh mereka berhak untuk menusuk matanya.” (HR. Muslim).',
  },
];

export const hellsData = [
  {
    name: 'Jahannam',
    description: 'Lapisan neraka yang paling dasar dan paling terkenal, yang diperuntukkan bagi orang-orang munafik dan orang kafir. Neraka ini memiliki tujuh pintu. Api neraka Jahannam jauh lebih panas dari api dunia, dan para penghuninya akan merasakan siksaan yang tiada henti.',
    source: 'QS. An-Nisa: 145 & QS. Al-Hijr: 43',
  },
  {
    name: 'Jahim',
    description: 'Neraka yang apinya berkobar-kobar sangat dahsyat. Ditempatkan bagi orang-orang musyrik yang mendustakan hari akhir. Mereka akan dilemparkan ke dalamnya dengan kondisi tidak berdaya.',
    source: 'QS. At-Takatsur: 6',
  },
  {
    name: 'Saqar',
    description: 'Neraka yang menghanguskan seluruh tubuh hingga ke tulang, tidak membiarkan satu bagian pun utuh. Ini diperuntukkan bagi orang yang tidak shalat, tidak memberi makan orang miskin, dan mendustakan hari pembalasan.',
    source: 'QS. Al-Muddatstsir: 26-29',
  },
  {
    name: 'Hawiyah',
    description: 'Neraka yang sangat dalam. Ditempatkan bagi orang yang timbangan amal kebaikannya ringan, yaitu orang-orang kafir. Mereka akan dilemparkan ke dasar neraka ini dan dicampakkan ke dalam api yang sangat panas.',
    source: 'QS. Al-Qari’ah: 9-11',
  },
  {
    name: 'Lazha',
    description: 'Neraka yang apinya bergejolak dan menyambar-nyambar, diperuntukkan bagi orang-orang yang berpaling dari kebenaran dan enggan mengeluarkan hartanya untuk berinfak.',
    source: 'QS. Al-Ma’arij: 15-18',
  },
  {
    name: 'Huthamah',
    description: 'Neraka yang apinya menghancurkan dan membakar sampai ke hati. Ini diperuntukkan bagi orang-orang yang suka mencela dan mengumpulkan harta tetapi tidak menginfakkannya di jalan Allah.',
    source: 'QS. Al-Humazah: 4-7',
  },
];

export const repentanceGuide = {
  title: 'Panduan Taubat Umum',
  steps: [
    {
      step: 'Menyesali Perbuatan Dosa',
      description: 'Penyesalan yang tulus dari hati adalah langkah pertama dan terpenting. Tanpa penyesalan, tobat tidak akan diterima.',
    },
    {
      step: 'Berhenti dari Perbuatan Dosa',
      description: 'Segera menghentikan perbuatan dosa yang telah dilakukan. Tidak ada gunanya menyesal jika masih terus melakukannya.',
    },
    {
      step: 'Bertekad untuk Tidak Mengulangi',
      description: 'Memiliki niat yang kuat untuk tidak akan kembali melakukan dosa yang sama di masa depan.',
    },
    {
      step: 'Memohon Ampunan kepada Allah',
      description: 'Memperbanyak istighfar (memohon ampunan) dan berdoa kepada Allah agar dosa-dosa diampuni.',
    },
    {
      step: 'Mengganti Kerugian (Jika Terkait Hak Orang Lain)',
      description: 'Jika dosa yang dilakukan terkait dengan hak orang lain (seperti hutang atau fitnah), wajib untuk meminta maaf dan mengembalikan hak tersebut.',
    },
  ],
  source: '“Wahai hamba-hamba-Ku yang telah melampaui batas terhadap diri mereka sendiri, janganlah kamu berputus asa dari rahmat Allah. Sesungguhnya Allah mengampuni dosa-dosa semuanya. Sesungguhnya Dia-lah Yang Maha Pengampun lagi Maha Penyayang.” (QS. Az-Zumar: 53).',
};
